### ISSUE TITLE
Uncaught IOException and Multiple File Event Threads

### ISSUE THREAD

**Issue by marshl** [marshl/Lobster#55]
2015-11-30 10:44:33.050 [INFO]: File change event of type Changed for file D:\Users\marsli\PharmCIS\trunk\FoxModules\CoreModules\PharmCIS\MAND_TEST.xml
2015-11-30 10:44:33.052 [INFO]: Starting file event thread
2015-11-30 10:44:33.052 [INFO]: File change event of type Changed for file D:\Users\marsli\PharmCIS\trunk\FoxModules\CoreModules\PharmCIS\MAND_TEST.xml
2015-11-30 10:44:33.076 [INFO]: Processing file event of type Changed for file D:\Users\marsli\PharmCIS\trunk\FoxModules\CoreModules\PharmCIS\MAND_TEST.xml
2015-11-30 10:44:33.091 [INFO]: Auto-updating file D:\Users\marsli\PharmCIS\trunk\FoxModules\CoreModules\PharmCIS\MAND_TEST.xml

2015-11-30 10:44:33.086 [INFO]: Starting file event thread
2015-11-30 10:44:33.099 [INFO]: File change event of type Changed for file D:\Users\marsli\PharmCIS\trunk\FoxModules\CoreModules\PharmCIS\MAND_TEST.xml
2015-11-30 10:44:33.099 [INFO]: Ignoring event, as it is already in the list.
2015-11-30 10:44:33.099 [INFO]: Processing file event of type Changed for file D:\Users\marsli\PharmCIS\trunk\FoxModules\CoreModules\PharmCIS\MAND_TEST.xml
2015-11-30 10:44:33.099 [INFO]: Auto-updating file D:\Users\marsli\PharmCIS\trunk\FoxModules\CoreModules\PharmCIS\MAND_TEST.xml

2015-11-30 10:44:33.288 [INFO]: Executing Update query: UPDATE envmgr.fox_components_env c SET c.data = :data WHERE c.name = 'MAND_TEST
2015-11-30 10:44:33.300 [ERROR]: Clob update failed for command: UPDATE envmgr.fox_components_env c SET c.data = :data WHERE c.name = 'MAND_TEST Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01756: quoted string not properly terminated
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at LobsterModel.Model.UpdateDatabaseClob(String fullpath, DBClobFile clobFile, DbConnection con) in C:\Users\Fivium\Documents\Lobster\LobsterModel\Model.cs:line 481
2015-11-30 10:44:33.358 [ERROR]: Unhandled Exception System.IO.IOException: The process cannot access the file '\\central.health\dfsuserenv\Users\User_03\marsli\Desktop\Debug\Debug\backup\2015-11-30_10-44-33MAND_TEST.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at LobsterModel.Model.DownloadClobDataToFile(DBClobFile clobFile, DbConnection con, String filename) in C:\Users\Fivium\Documents\Lobster\LobsterModel\Model.cs:line 651
   at LobsterModel.Model.BackupClobFile(DbConnection con, DBClobFile clobFile, String fullpath) in C:\Users\Fivium\Documents\Lobster\LobsterModel\Model.cs:line 414
   at LobsterModel.Model.UpdateClobWithExternalFile(String targetFilename, String sourceFilename) in C:\Users\Fivium\Documents\Lobster\LobsterModel\Model.cs:line 109
   at LobsterModel.Model.SendUpdateClobMessage(String fullpath) in C:\Users\Fivium\Documents\Lobster\LobsterModel\Model.cs:line 127
   at LobsterModel.DatabaseConnection.ProcessFileEvent(FileSystemEventArgs e) in C:\Users\Fivium\Documents\Lobster\LobsterModel\DatabaseConnection.cs:line 284
   at LobsterModel.DatabaseConnection.ProcessAllFileEvents() in C:\Users\Fivium\Documents\Lobster\LobsterModel\DatabaseConnection.cs:line 227
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by marshl** [comment]
See http://stackoverflow.com/questions/14430999/allow-async-method-to-be-called-only-one-instance-at-a-time

**Comment by marshl** [comment]
also see http://stackoverflow.com/questions/14693451/queue-implementation-of-file-monitoring-and-send-them-to-a-web-service
and http://stackoverflow.com/questions/13410738/creating-a-queue-to-handle-jobs-triggered-by-filesystemwatcher
