### ISSUE TITLE
Crash on Network Disconnect

### ISSUE THREAD

**Issue by marshl** [marshl/Lobster#99]
```
2016-08-09 19:30:17.628 [INFO]: Executing Update query: 
BEGIN
  xviewmgr.xview.load(:clob, 'C');  
  COMMIT;
END;

2016-08-09 19:41:11.771 [ERROR]: Unhandled Exception Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12537: Network Session: End of file ---> OracleInternal.Network.NetworkException (0x000030F9): ORA-12537: Network Session: End of file
   at OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   at OracleInternal.TTC.OraBufReader.GetDataFromNetwork()
   at OracleInternal.TTC.OraBufReader.Read(Boolean bIgnoreData)
   at OracleInternal.TTC.TTCSimpleOperations.ReadResponse()
   at Oracle.ManagedDataAccess.Client.OracleException.HandleError(OracleTraceLevel level, OracleTraceTag tag, Exception ex, OracleLogicalTransaction oracleLogicalTransaction)
   at OracleInternal.TTC.TTCSimpleOperations.ReadResponse()
   at OracleInternal.ServiceObjects.OracleTransactionImpl.Rollback()
   at Oracle.ManagedDataAccess.Client.OracleTransaction.Rollback()
   at LobsterModel.Model.UpdateDatabaseClob(DatabaseConnection databaseConnection, String fullpath, DBClobFile clobFile, ClobDirectory clobDir, DbConnection oracleConnection) in C:\Users\Fivium\Projects\Lobster\LobsterModel\Model.cs:line 580
   at LobsterModel.Model.UpdateClobWithExternalFile(DatabaseConnection databaseConnection, ClobDirectory clobDir, String targetFilename, String sourceFilename) in C:\Users\Fivium\Projects\Lobster\LobsterModel\Model.cs:line 87
   at LobsterWpf.MainWindow.PushButton_Click(Object sender, RoutedEventArgs e) in C:\Users\Fivium\Projects\Lobster\LobsterWpf\Views\MainWindow.xaml.cs:line 310
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at LobsterWpf.App.Main() in C:\Users\Fivium\Projects\Lobster\LobsterWpf\obj\Release\App.g.cs:line 0
2016-08-09 19:41:11.771 [INFO]: Lobster Stopped
ication.RunInternal(Window window)
   at LobsterWpf.App.Main() in C:\Users\Fivium\Projects\Lobster\LobsterWpf\obj\Release\App.g.cs:line 0
2016-08-09 19:41:11.458 [INFO]: Lobster Stopped
```

**Comment by marshl** [comment]
Fixed as part of Lobster 3
